-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 22:25:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sakila_DW
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sakila_DW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sakila_DW` DEFAULT CHARACTER SET utf8 ;
USE `sakila_DW` ;

-- -----------------------------------------------------
-- Table `sakila_DW`.`dimCustomer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_DW`.`dimCustomer` (
  `customer_key` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` SMALLINT(5) UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(50) NOT NULL,
  `address2` VARCHAR(50) NULL DEFAULT NULL,
  `district` VARCHAR(20) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`customer_key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_DW`.`dimDate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_DW`.`dimDate` (
  `date_key` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `year` SMALLINT(6) NOT NULL,
  `quarter` TINYINT(4) NOT NULL,
  `month` TINYINT(4) NOT NULL,
  `day` TINYINT(4) NOT NULL,
  `week` TINYINT(4) NOT NULL,
  `is_weekend` TINYINT(1) NULL DEFAULT NULL,
  `is_holiday` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`date_key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_DW`.`dimMovie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_DW`.`dimMovie` (
  `movie_key` INT(11) NOT NULL AUTO_INCREMENT,
  `film_id` SMALLINT(5) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_year` YEAR(4) NULL DEFAULT NULL,
  `language` VARCHAR(20) NOT NULL,
  `original_language` VARCHAR(20) NULL DEFAULT NULL,
  `rental_duration` TINYINT(3) UNSIGNED NOT NULL,
  `length` SMALLINT(5) UNSIGNED NOT NULL,
  `rating` VARCHAR(5) NOT NULL,
  `special_features` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`movie_key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_DW`.`dimStore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_DW`.`dimStore` (
  `store_key` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` SMALLINT(5) UNSIGNED NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `address2` VARCHAR(50) NULL DEFAULT NULL,
  `district` VARCHAR(20) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `region` VARCHAR(10) NULL DEFAULT NULL,
  `manager_first_name` VARCHAR(45) NOT NULL,
  `manager_last_name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`store_key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_DW`.`factSales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_DW`.`factSales` (
  `sales_key` INT(11) NOT NULL AUTO_INCREMENT,
  `date_key` INT(11) NOT NULL,
  `customer_key` INT(11) NOT NULL,
  `movie_key` INT(11) NOT NULL,
  `store_key` INT(11) NOT NULL,
  `sales_amount` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`sales_key`),
  INDEX `fk_date` (`date_key` ASC),
  INDEX `fk_customer` (`customer_key` ASC),
  INDEX `fk_movie` (`movie_key` ASC),
  INDEX `fk_store` (`store_key` ASC),
  CONSTRAINT `factsales_ibfk_1`
    FOREIGN KEY (`date_key`)
    REFERENCES `sakila_DW`.`dimDate` (`date_key`),
  CONSTRAINT `factsales_ibfk_2`
    FOREIGN KEY (`customer_key`)
    REFERENCES `sakila_DW`.`dimCustomer` (`customer_key`),
  CONSTRAINT `factsales_ibfk_3`
    FOREIGN KEY (`movie_key`)
    REFERENCES `sakila_DW`.`dimMovie` (`movie_key`),
  CONSTRAINT `factsales_ibfk_4`
    FOREIGN KEY (`store_key`)
    REFERENCES `sakila_DW`.`dimStore` (`store_key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
